/** Uses the STT audio clock and never opens another microphone. */
class RecognitionSession {
 constructor(renderer){this.renderer=renderer;this.generation=0;this.words=[];this.turns=[];this.askedFaces=new Map();this.logged=new Set();this.createPrompt();}
 send(session){this.renderer.state.wsHandler?.send({type:'session.update',session:{allow_recording:false,...session}});}
 start(){this.stop();const generation=this.generation;const update=async()=>{try{const status=await window.nodie.liveSpeakerStatus();if(generation!==this.generation)return;const enabled=Boolean(status.enabled)&&!this.renderer.state.isMuted;if(this.enabled&&!enabled){window.nodie.cancelRecognition?.().catch(()=>{});this.clearPrompt();}this.enabled=enabled;this.send({speaker_tracking_enabled:enabled});}catch{this.enabled=false;this.send({speaker_tracking_enabled:false});}};void update();this.poll=setInterval(update,5000);}
 stop(){++this.generation;clearInterval(this.poll);clearTimeout(this.attemptTimer);this.enabled=false;this.words=[];this.turns=[];this.assistantText='';this.previousAssistant='';this.logged=new Set();this.speaking=false;this.clearPrompt();this.send({speaker_tracking_enabled:false,speaker_observation:null,face_observation:null,recognition_feedback:null});window.nodie?.cancelRecognition?.().catch(()=>{});window.nodie?.cancelSpeakers?.().catch(()=>{});}
 clearPrompt(){clearTimeout(this.expiry);this.pending=null;if(this.prompt)this.prompt.hidden=true;}
 event(data){
  if(data.type==='nodie.speaker_audio'){void this.analyse(data);return;}
  if(data.type==='nodie.word_end'){const word=this.words.at(-1)||this.turns.at(-1)?.words.at(-1);if(word&&Number.isFinite(data.end_time)&&data.end_time>word.start)word.end=data.end_time;this.schedule();return;}
  if(data.type==='nodie.attributed_words'){
   this.renderer.transcript?.attribute?.(data.words);
   for(const word of data.words||[]){for(const target of [...this.words,...this.turns.flatMap(t=>t.words)])if(target.start===word.start&&target.text===word.text)Object.assign(target,word);
    const key=word.start+':'+(word.profile||'?');if(this.logged.has(key))continue;this.logged.add(key);if(this.logged.size>200)this.logged.delete(this.logged.values().next().value);this.renderer.debugStream?.add('Speaker words',`${word.name||(word.profile?'Unknown speaker':'Unattributed')}: ${word.text}`);
   }this.schedule();return;
  }
  if(data.type==='response.text.delta'&&typeof data.delta==='string')this.assistantText=((this.assistantText||'')+data.delta).slice(-2000);
  if(data.type==='conversation.item.input_audio_transcription.delta'&&typeof data.delta==='string'&&Number.isFinite(data.start_time)){if(!this.words.length)this.previousAssistant=this.assistantText||'';this.words.push({text:data.delta,start:data.start_time});this.words=this.words.slice(-100);}
  if(data.type==='response.created'){if(this.words.length)this.turns.push({words:this.words,previousAssistant:this.previousAssistant,at:Date.now()});this.turns=this.turns.slice(-3);this.words=[];this.assistantText='';this.speaking=true;}
  if(['response.done','response.audio.done','response.cancelled','unmute.interrupted_by_vad'].includes(data.type)){this.speaking=false;this.schedule();}
 }
 schedule(){clearTimeout(this.attemptTimer);if(!this.speaking)this.attemptTimer=setTimeout(()=>void this.propose(),300);}
 async analyse(data){if(!this.enabled||this.busy||typeof data.audio!=='string'||data.audio.length>350000||!Number.isFinite(data.start_time)||!Number.isFinite(data.end_time)||data.start_time<0||data.end_time<=data.start_time||data.end_time-data.start_time>5)return;const generation=this.generation;this.busy=true;try{const bytes=Uint8Array.from(atob(data.audio),c=>c.charCodeAt(0));const observation=await window.nodie.analyseSpeakers(bytes,{start:data.start_time,end:data.end_time});if(generation!==this.generation||!this.enabled||!observation)return;this.send({speaker_observation:{...observation,start_time:data.start_time,end_time:data.end_time}});this.schedule();}catch{}finally{this.busy=false;}}
 faces(result){const faces=result?.state==='ready'?result.faces:[];this.send({face_observation:faces.map(f=>{const mayAskName=!f.name&&!f.uncertain&&f.id&&Date.now()-(this.askedFaces.get(f.id)||0)>300000;if(mayAskName)this.askedFaces.set(f.id,Date.now());return {profileId:f.name&&!f.uncertain?f.id:null,name:f.name||null,uncertain:true,mayAskName:Boolean(mayAskName)};})});}
 async propose(){if(this.proposing||this.pending||this.speaking)return;const turn=this.turns.find(t=>!t.attempted&&Date.now()-t.at<15000&&t.words.every(w=>Number.isFinite(w.end)));if(!turn)return;turn.attempted=true;const generation=this.generation;this.proposing=true;try{const result=await window.nodie.proposeRecognitionName({text:turn.words.map(w=>w.text).join(' ').slice(0,2000),start:turn.words[0].start,end:turn.words.at(-1).end,previousAssistant:turn.previousAssistant});if(['awaiting-observation','deferred'].includes(result.status))turn.attempted=false;if(generation!==this.generation||result.status!=='pending')return;this.showPrompt(result);}catch{}finally{this.proposing=false;}}
 showPrompt(result){this.pending=result;clearTimeout(this.expiry);this.expiry=setTimeout(()=>{if(this.pending===result)void this.confirm(false);},60000);this.label.textContent=`Use “${result.name}” for ${result.kind==='face'?'the sole person visible when introduced':'the voice in that introduction'}? Confirm here to save.`;this.prompt.hidden=false;this.send({recognition_feedback:{status:'pending',kind:result.kind,name:result.name}});}
 async confirm(accepted){const pending=this.pending;if(!pending)return;this.clearPrompt();try{const result=await window.nodie.confirmRecognitionName(pending.token,accepted);this.send({recognition_feedback:{status:result.status,kind:pending.kind,name:pending.name}});this.schedule();this.renderer.debugStream?.add('Naming',`${pending.kind}: ${pending.name} — ${result.status}`);}catch{this.renderer.showNotification('Profile name could not be saved.','error');}}
 createPrompt(){this.prompt=document.createElement('div');this.prompt.id='recognition-confirm';this.prompt.hidden=true;this.prompt.setAttribute('role','alertdialog');this.prompt.setAttribute('aria-label','Confirm recognition label');this.label=document.createElement('span');this.prompt.append(this.label);for(const [text,value] of [['Confirm',true],['Cancel',false]]){const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=()=>void this.confirm(value);this.prompt.append(b);}document.body.append(this.prompt);}
}
if(typeof window!=='undefined')window.RecognitionSession=RecognitionSession;
if(typeof module!=='undefined')module.exports={RecognitionSession};

if(typeof window!=='undefined')window.addEventListener('DOMContentLoaded',()=>{if(window.NodieRenderer&&window.nodie?.proposeRecognitionName){const r=window.NodieRenderer;r.recognition ||= new RecognitionSession(r);window.nodie.onRecognitionProposal?.(p=>r.recognition.showPrompt(p));}});
