const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const {EventJournal,PresenceEvents}=require('../../lib/event-journal');
test('journal retention, deduplication, clear epoch and bounded validation',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'nodie-journal-'));let now=Date.parse('2026-09-24T10:00:00Z');const j=new EventJournal(path.join(dir,'journal.json'),{now:()=>now});try{const epoch=(await j.load()).epoch;const event={source:'vision',kind:'appeared',subject:'grey cat'};assert.equal(await j.append(event,epoch),'saved');assert.equal(await j.append(event,epoch),'duplicate');now+=31*86400000;assert.equal((await j.load()).events.length,0);await j.clear();assert.equal(await j.append(event,epoch),'stale');assert.throws(()=>j.append({...event,subject:'bad\ntext'}));assert.equal((await fs.stat(j.file)).mode&0o777,0o600);}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('presence requires repeated evidence and camera reset never invents departure',async()=>{let now=0;const events=[];const p=new PresenceEvents({append:async e=>events.push(e)},{now:()=>now});await p.observe(['grey cat']);assert.equal(events.length,0);now=15000;await p.observe(['grey cat']);assert.equal(events[0].kind,'appeared');now=30000;await p.observe([]);now=45000;await p.observe([]);assert.equal(events.length,1);now=60000;await p.observe([]);assert.equal(events[1].kind,'out-of-view');p.reset();now=90000;await p.observe([]);assert.equal(events.length,2);});
test('cancelled and failed vision calls cannot create departures; calls are rate limited',async()=>{const {JournalVision}=require('../../lib/journal-vision');let resolve,calls=0,now=0;const j={load:async()=>({epoch:'a',enabled:true}),append:async()=>assert.fail('No event expected')};const vision={cancel(){},observe:()=>{calls++;return new Promise(r=>resolve=r);}};const v=new JournalVision({vision,journal:j,now:()=>now});const pending=v.analyse(new Uint8Array());await Promise.resolve();await Promise.resolve();v.cancel();resolve({status:'ready',subjects:['cat']});await pending;await v.analyse(new Uint8Array());assert.equal(calls,1);now=16000;vision.observe=async()=>({status:'unavailable'});await v.analyse(new Uint8Array());assert.equal(v.presence.present.size,0);});

test('corrupt journal can be cleared; unsupported spoken dates never return today',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'nodie-journal-'));const j=new EventJournal(path.join(dir,'journal.json'));try{await fs.writeFile(j.file,'broken');await j.clear();assert.equal((await j.load()).retentionDays,30);assert.equal((await j.reference('What happened Monday?')).status,'unsupported-date');assert.equal(await j.reference('What is the weather today?'),null);}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('recognition result survives unavailable journal',async()=>{const {JournalRecorder}=require('../../lib/journal-recorder');const r=new JournalRecorder({load:async()=>{throw Error('locked')}});const expected={state:'ready',faces:[]};assert.equal(await r.capture(async()=>expected,()=>[]),expected);});
test('structured vision accepts unfamiliar species and appearances without a household vocabulary',async()=>{
 const {VisionAnalysis}=require('../../lib/vision-analysis');let data={people:1,animals:[{kind:'dog',appearance:'brown curly coat'},{kind:'parrot',appearance:'green and yellow'},{kind:'rabbit',appearance:'spotted'},{kind:'cat',appearance:'tortoiseshell'}]};
 const v=new VisionAnalysis({fetchImpl:async()=>new Response(JSON.stringify({message:{content:JSON.stringify(data)}}))});const image=new Uint8Array([255,216,255,217]);
 assert.deepEqual((await v.observe(image)).subjects,['Unidentified person','brown curly coat dog','green and yellow parrot','spotted rabbit','tortoiseshell cat']);
 for(const invalid of [{people:0,animals:[{kind:'dog',appearance:'brown',name:'Rover'}]},{people:0,animals:[{kind:'dog',appearance:'x'.repeat(101)}]},{people:0,animals:[{kind:'dog',appearance:'bad\ntext'}]},{people:0,animals:Array(9).fill({kind:'dog',appearance:''})},null]){data=invalid;assert.equal((await v.observe(image)).status,'unavailable');}
});
test('journal date selection respects London midnight and explicit week anchor',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'nodie-journal-'));const now=Date.parse('2026-09-24T00:30:00Z'),j=new EventJournal(path.join(dir,'journal.json'),{now:()=>now,timezone:'Europe/London'});try{await j.load();await j.append({source:'vision',kind:'appeared',subject:'grey cat',at:Date.parse('2026-09-23T23:30:00Z')});assert.equal((await j.reference('What happened today?')).events.length,1);assert.equal((await j.reference('What happened yesterday?')).events.length,0);const week=await j.reference('What happened last week through 2026-09-20?');assert.equal(week.from,'2026-09-14');assert.equal(week.through,'2026-09-20');}finally{await fs.rm(dir,{recursive:true,force:true});}});

test('journal publishes the configured timezone for readers on other machines',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'nodie-journal-'));try{const j=new EventJournal(path.join(dir,'journal.json'),{timezone:'America/Los_Angeles',now:()=>Date.parse('2026-09-24T01:00:00Z')});assert.equal((await j.load()).timezone,'America/Los_Angeles');assert.equal((await j.reference('What happened today?')).through,'2026-09-23');assert.throws(()=>new EventJournal(j.file,{timezone:'invalid/timezone'}));}finally{await fs.rm(dir,{recursive:true,force:true});}});
